version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: